### ISSUE TITLE
CommonJS and UMD bundles cannot be used with IE10 and PhantomJS without transpilation

### ISSUE THREAD

**Issue by evangalen** [styfle/copee#33]
The CommonJS (`copee.js`) and UMD (`copee.umd.js`) bundles in `dist` folder cannot be used in IE10 as well as PhantomJS due to the fact that `let` and `const` is being used (although the rest of the code appears to be correct ES5 code).

The bundles happens to we working (using the CommonJS bundle in my case) in IE11 because it offers (incomplete) support for `let` and `const`.

**Comment by styfle** [comment]
It actually works fine on IE 11, which supports `let` and `const` according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const#Browser_compatibility) and I also verified this myself.

It looks like the [demo page](https://copee.ceriously.com) fails in IE 11 because of the arrow functions.

**Comment by styfle** [comment]
I have no plans to support browsers with CommonJS because CJS is made available for Node.js, not the browser.

I have no plans to support IE 10 or PhantomJS because they are both end-of-life and have predecessors:

- IE 10 => IE 11
- PhantomJS => [Puppeteer](https://github.com/GoogleChrome/puppeteer)

Sorry for the inconvenience, thanks for reporting this though

**Comment by evangalen** [comment]
Thanks for your quick response and also for updating the readme.

You are right about the fact that the UMD build works fine on IE11.
But MDN is actually incorrect about the fact that IE11 "completely" supports `let` and `const`,
since IE11 doesn't correctly implement the "for/for-in loop iteration scope"; see: https://kangax.github.io/compat-table/es6/

Then again, the current usage of `let` and `const` in Copee is fully supported by IE11.
